[[EMPRESAS]]
empresa = "MEGA NET"
login = "38181"
senha = "FWkIhmUxzVo0"

[[EMPRESAS]]
empresa = "SONAVOIP"
login = "7"
senha = "x@VTmp#oStEdJ45"

[[EMPRESAS]]
empresa = "UPNET"
login = "30235"
senha = "Xi%juDEMwQzP69d"

[[EMPRESAS]]
empresa = "MARANGUAPE"
login = "73231"
senha = "oeEh30EopqfK"

[[EMPRESAS]]
empresa = "LIVRE"
login = "53411"
senha = "p#LcDa2G@Vt0jSq"

[[EMPRESAS]]
empresa = "BIP VIP PIZZARIA"
login = "25205"
senha = "yLC$mnj3x2aTEAw"

[[EMPRESAS]]
empresa = "Z.RO BANK"
login = "97361"
senha = "CO8btAFQ"

[[EMPRESAS]]
empresa = "ANESTESIL"
login = "50693"
senha = "!RCJi%6Ph7ITpQm"

[[EMPRESAS]]
empresa = "CEO"
login = "46343"
senha = "rh@WMEKYPiNIkdS"

[[EMPRESAS]]
empresa = "CEOL"
login = "14451"
senha = "VAIXrdYkqqjL"

[[EMPRESAS]]
empresa = "DIAGMED"
login = "60101"
senha = "cFUd@$XNoLu2l6g"

[[EMPRESAS]]
empresa = "ESPAÇO VIDA"
login = "19151"
senha = "Btmsi$j!CGL8fyr"

[[EMPRESAS]]
empresa = "PRONTOCLINICA"
login = "50653"
senha = "4VtBMvIxi1NHQq6"

[[EMPRESAS]]
empresa = "PSICOMED"
login = "37785"
senha = "2SGd1Ao$kQyDXz7"

[[EMPRESAS]]
empresa = "RINNUS"
login = "46323"
senha = "lS85cY0%dnegsLy"

[[EMPRESAS]]
empresa = "SÃO MARCOS"
login = "80811"
senha = "QF#tP%pvfabZrBA"

[[EMPRESAS]]
empresa = "MINHA CONSULTA"
login = "31885"
senha = "5yv7J9XUg1juRlC"

[[EMPRESAS]]
empresa = "ALPHAVIEW"
login = "94751"
senha = "g07UYWOcN9YH"

[[EMPRESAS]]
empresa = "DOPPLER"
login = "101411"
senha = "HPvc13Ld"

[[EMPRESAS]]
empresa = "VITALI"
login = "89381"
senha = "F0emHjPV"

[[EMPRESAS]]
empresa = "HOPAY"
login = "106021"
senha = "UnihJCZuymUC"

[[EMPRESAS]]
empresa = "DIETNET"
login = "101201"
senha = "tKOMU59q"
